### ISSUE TITLE
Blurry text in subwindows

### ISSUE THREAD

**Issue by TheLonelyAdventurer** [AkshaySG14/haystack-public#4]
I really like Haystack, but zooming in just doesn't work well.

![immagine](https://github.com/user-attachments/assets/68bf0b7e-dcff-4513-aae3-b3f9b915bc13)

The text appears blurred.

I can't see your code, but maybe there is something weird with the canvas rendering context not being updated correctly. 

![immagine](https://github.com/user-attachments/assets/5f5af8bd-f632-4ea4-8013-988b8447912b)

If I force the subwindow to update by resizing it, the title gets correctly rendered instead but not the code.

Thank you for your work; I'm willing to provide more information if you need it.

**Comment by zhangjiangqige** [comment]
For me the text is always blurry on an external monitor which isn't retina, and is always clear on my macbook's built in screen

Making macbook's screen be a mirror of the external monitor didn't help. And I unfortunately don't have a retina external monitor to compare

**Comment by AkshaySG14** [comment]
Yeah ugh this is a big issue that I wish to address soon. There is something weird with decimal widths/heights that is the issue here.

**Comment by AkshaySG14** [comment]
@TheLonelyAdventurer @zhangjiangqige It seems like this error is occurring on non-MacOS laptop/computer screens? I think I know of a stopgap measure but could y'all confirm?

**Comment by TheLonelyAdventurer** [comment]
@AkshaySG14 I confirm I am using Windows 11, with a non-retina fhd display.

Are you thinking of the high-dpi thing? In which case, I think you can just premultiply calculations with the pixel depth ratio...

**Comment by zhangjiangqige** [comment]
> this error is occurring on non-MacOS laptop/computer screens

if you meant a non-Apple monitor connected to a Macbook, then yes

to be clear, my setup is a 2019 Macbook and a Dell monitor, and the text is blurry on Dell

**Comment by coljac** [comment]
On Linux, here's what I see in Haystack and VSCode. First Code, then Haystack. Haystack doesn't look great!
![ksnip_20240826-144346](https://github.com/user-attachments/assets/5d26f0ef-79ac-4f91-9379-36a469f6bba6)
![ksnip_20240826-144222](https://github.com/user-attachments/assets/fecf79d2-982d-4b82-8d75-e6a638d495cf)

**Comment by AkshaySG14** [comment]
@coljac Is this even on normal zoom levels?

**Comment by coljac** [comment]
@AkshaySG14 Yes: Does this provide more context?
![ksnip_20240826-165333](https://github.com/user-attachments/assets/6388fb81-f895-437c-bd55-356aed35d051)
Zoom is reset. Font size is Deja Vu Sans Mono 20pt

**Comment by AkshaySG14** [comment]
This should be fixed on the current version of Haystack on the website! Could you try it and let me know?

**Comment by coljac** [comment]
@AkshaySG14 No dice for me alas: This is with 0.14 which I just grabbed. The text looks very soft and blurry.


![ksnip_20240827-170959](https://github.com/user-attachments/assets/fe89e0da-c548-438f-8c96-2e3d8f848bc8)

**Comment by AkshaySG14** [comment]
Ah shoot something went wrong with our Linux deploy. It should be 0.15. Will get back to you ASAP.

**Comment by AkshaySG14** [comment]
@coljac Just updated Linux. Does it work now?

**Comment by TheLonelyAdventurer** [comment]
> This should be fixed on the current version of Haystack on the website! Could you try it and let me know?

Downloaded most recent from website zip. Nothing seems to have changed; I still see the blurry text

**Comment by AkshaySG14** [comment]
@TheLonelyAdventurer you are on Windows correct? Unfortunately we’re still working on the fix for Windows.

**Comment by coljac** [comment]
> @coljac Just updated Linux. Does it work now?

Yes, this looks fine now.

**Comment by coljac** [comment]
I take it back, I'm afraid there is still something going on. I tried it on my work machine and it seemed fine... but comparing it here to VSCode and Cursor, here's what I see - at the same scale, Haystack, Code, Cursor:

![ksnip_20240828-204830](https://github.com/user-attachments/assets/19dfce73-d2a5-45f2-bcac-39d97ecc215e)

**Comment by AkshaySG14** [comment]
Is this on a monitor? I think I finally figured out the fix and will update here when I have it ready.

**Comment by coljac** [comment]
> Is this on a monitor? I think I finally figured out the fix and will update here when I have it ready.

That's a screenshot, not a photo, if that's the question. So those are the actual pixels.

**Comment by AkshaySG14** [comment]
OK I believe this should be definitively fixed now. Please lmk if that's not the case.

**Comment by coljac** [comment]
Looks good now. 😃
